server:
  port: 9001
spring:
  application:
    name: org-service  #服务名，将注册到eureka注册中心
eureka:
  instance: 
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/register-center/  #注册地址，eureka服务地址
      
security:  basic:    enabled: false      
      
      